# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, alex, binary, dataDefault, derive, filepath, hashable
, hspec, lens, ooPrototypes, pointedlist, QuickCheck, regexBase
, regexTdfa, transformersBase, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "yi-language";
  version = "0.1.0.3";
  sha256 = "1gyb7hpmm35ka0r3qdka1b813jf71zg0rbijk3zz79nsq4jhzid6";
  buildDepends = [
    binary dataDefault derive hashable lens ooPrototypes pointedlist
    regexBase regexTdfa transformersBase unorderedContainers
  ];
  testDepends = [
    binary dataDefault derive filepath hashable hspec lens pointedlist
    QuickCheck regexBase regexTdfa transformersBase unorderedContainers
  ];
  doCheck = false;
  buildTools = [ alex ];
  meta = {
    homepage = "https://github.com/yi-editor/yi-language";
    description = "Collection of language-related Yi libraries";
    license = self.stdenv.lib.licenses.gpl2;
    platforms = self.ghc.meta.platforms;
  };
})
