# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, deepseq, fingertree, hspec, QuickCheck
, quickcheckInstances, text
}:

cabal.mkDerivation (self: {
  pname = "yi-rope";
  version = "0.4.0.0";
  sha256 = "1sdn4jk3xnc00h4wcl1456dgj12m4516kfl5s7z9bzs5riaih8wd";
  buildDepends = [ binary deepseq fingertree text ];
  testDepends = [ hspec QuickCheck quickcheckInstances text ];
  meta = {
    description = "A rope data structure used by Yi";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
