# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, Cabal, cautiousFile, concreteTyperep, dataDefault
, derive, Diff, dlist, dyre, filepath, hashable, hint
, HUnit, lens, mtl, ooPrototypes, parsec, pointedlist
, QuickCheck, random, regexBase, regexTdfa, safe, semigroups, split
, tagged, tasty, tastyHunit, tastyQuickcheck, text, time
, transformersBase, unixCompat, unorderedContainers, utf8String
, vty, wordTrie, xdgBasedir, yiLanguage, yiRope
}:

cabal.mkDerivation (self: {
  pname = "yi";
  version = "0.9.1";
  src = /home/cray/yi-git/yi;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    binary Cabal cautiousFile concreteTyperep dataDefault derive Diff
    dlist dyre filepath hashable hint lens mtl ooPrototypes
    parsec pointedlist QuickCheck random regexBase regexTdfa safe
    semigroups split tagged text time transformersBase unixCompat
    unorderedContainers utf8String vty wordTrie xdgBasedir yiLanguage
    yiRope
  ];
  testDepends = [
    filepath HUnit lens QuickCheck semigroups tasty tastyHunit
    tastyQuickcheck text yiLanguage yiRope
  ];
  configureFlags = "-fvty";
  meta = {
    homepage = "http://haskell.org/haskellwiki/Yi";
    description = "The Haskell-Scriptable Editor";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
