# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, filepath, lens, mtl, ooPrototypes, split, text, time
, transformersBase, yi, yiLanguage, yiRope
}:

cabal.mkDerivation (self: {
  pname = "yi-contrib";
  version = "0.9.1";
  src = /home/cray/yi-git/yi-contrib;
  buildDepends = [
    filepath lens mtl ooPrototypes split text time transformersBase yi
    yiLanguage yiRope
  ];
  meta = {
    homepage = "http://haskell.org/haskellwiki/Yi";
    description = "Add-ons to Yi, the Haskell-Scriptable Editor";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
