# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataDefault, extensibleExceptions, filepath, mtl
, QuickCheck, setlocale, utf8String, X11
}:

cabal.mkDerivation (self: {
  pname = "xmonad";
  version = "0.12";
  src = /home/cray/xmonad;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    dataDefault extensibleExceptions filepath mtl setlocale utf8String
    X11
  ];
  testDepends = [ extensibleExceptions QuickCheck X11 ];
  postInstall = ''
    shopt -s globstar
    mkdir -p $out/share/man/man1
    mv "$out/"**"/man/"*.1 $out/share/man/man1/
  '';
  patches = [
    # Patch to make xmonad use XMONAD_{GHC,XMESSAGE} (if available).
    ./xmonad_ghc_var_0.11.patch
  ];
  doCheck = false;
  meta = {
    homepage = "http://xmonad.org";
    description = "A tiling window manager";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
