# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, alsaCore, alsaMixer, dbus, filepath, hinotify, HTTP
, libXrandr, mtl, parsec, regexCompat, stm, time, timezoneOlson
, timezoneSeries, utf8String, wirelesstools, X11, X11Xft
, libXpm
}:

cabal.mkDerivation (self: {
  pname = "xmobar";
  version = "0.21";
  src = /home/cray/xmobar;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    alsaCore alsaMixer dbus filepath hinotify HTTP mtl parsec
    regexCompat stm time timezoneOlson timezoneSeries utf8String X11
    X11Xft
  ];
  extraLibraries = [ libXrandr wirelesstools libXpm ];
  configureFlags = "-fall_extensions";
  meta = {
    homepage = "http://xmobar.org";
    description = "A Minimalistic Text Based Status Bar";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
