# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, extensibleExceptions, filepath, mtl, random, utf8String
, X11, X11Xft, xmonad
}:

cabal.mkDerivation (self: {
  pname = "xmonad-contrib";
  version = "0.12";
  src = /home/cray/XMonadContrib;
  buildDepends = [
    extensibleExceptions filepath mtl random utf8String X11 X11Xft
    xmonad
  ];
  meta = {
    homepage = "http://xmonad.org/";
    description = "Third party extensions for xmonad";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
